const mockTools = [
  {
    id: 1,
    name: "ChatGPT",
    description: "A powerful AI assistant by OpenAI with multimodal capabilities.",
    category: "Chat",
    tags: ["NLP", "Assistant", "Chatbot"],
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    url: "https://chat.openai.com/",
    upvotes: 120,
    bookmarked: false
  },
  {
    id: 2,
    name: "RunwayML",
    description: "Create and edit videos using AI.",
    category: "Image & Video",
    tags: ["Video", "Generation", "Creative"],
    logo: "https://runwayml.com/logo.png",
    url: "https://runwayml.com/",
    upvotes: 89,
    bookmarked: false
  },
  {
    id: 3,
    name: "Claude",
    description: "Advanced conversational AI developed by Anthropic.",
    category: "Chat",
    tags: ["NLP", "Chatbot", "Assistant"],
    logo: "https://www.anthropic.com/images/favicon/favicon-32x32.png",
    url: "https://claude.ai/",
    upvotes: 100,
    bookmarked: false
  },
  {
    id: 4,
    name: "DeepSeek",
    description: "Open-source AI model focused on math, code, and reasoning tasks.",
    category: "Code",
    tags: ["Open Source", "Coding", "Reasoning"],
    logo: "https://avatars.githubusercontent.com/u/171911116?s=200&v=4",
    url: "https://github.com/deepseek-ai",
    upvotes: 75,
    bookmarked: false
  },
  {
    id: 5,
    name: "Google Gemini",
    description: "Google's powerful multimodal assistant integrated across products.",
    category: "Chat",
    tags: ["Assistant", "Multimodal", "Google"],
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Google_Gemini_logo.svg/32px-Google_Gemini_logo.svg.png",
    url: "https://gemini.google.com/",
    upvotes: 95,
    bookmarked: false
  },

  {
  id: 6,
  name: "Midjourney",
  description: "AI-based image generation tool with artistic styles.",
  category: "Image",
  tags: ["Art", "Image Generation", "Creative"],
  logo: "https://midjourney.com/favicon.ico",
  url: "https://midjourney.com/",
  upvotes: 140,
  bookmarked: false
},
{
  id: 7,
  name: "Ideogram",
  description: "Create typographic images using AI prompts.",
  category: "Image",
  tags: ["Typography", "Image", "Creative"],
  logo: "https://ideogram.ai/favicon.ico",
  url: "https://ideogram.ai/",
  upvotes: 110,
  bookmarked: false
},
{
  id: 8,
  name: "Perplexity AI",
  description: "An AI-powered answer engine and research assistant.",
  category: "Research",
  tags: ["Search", "Research", "Assistant"],
  logo: "https://www.perplexity.ai/favicon.ico",
  url: "https://www.perplexity.ai/",
  upvotes: 130,
  bookmarked: false
},
{
  id: 9,
  name: "Phind",
  description: "AI search engine built for developers.",
  category: "Code",
  tags: ["Developer", "Search", "Programming"],
  logo: "https://phind.com/favicon.ico",
  url: "https://phind.com/",
  upvotes: 98,
  bookmarked: false
},
{
  id: 10,
  name: "Pika",
  description: "AI tool to generate and edit videos with ease.",
  category: "Video",
  tags: ["Video", "Generation", "AI"],
  logo: "https://pika.art/favicon.ico",
  url: "https://pika.art/",
  upvotes: 102,
  bookmarked: false
},

{
  id: 11,
  name: "Hugging Face",
  description: "Home of open-source machine learning models and datasets.",
  category: "Platform",
  tags: ["ML", "Models", "Datasets"],
  logo: "https://huggingface.co/front/assets/huggingface_logo-noborder.svg",
  url: "https://huggingface.co/",
  upvotes: 115,
  bookmarked: false
},
{
  id: 12,
  name: "Leonardo AI",
  description: "AI image generator for game assets and concept art.",
  category: "Image",
  tags: ["Game Dev", "Image", "Art"],
  logo: "https://app.leonardo.ai/favicon.ico",
  url: "https://leonardo.ai/",
  upvotes: 108,
  bookmarked: false
},
{
  id: 13,
  name: "OpenArt",
  description: "Create and explore AI-generated art.",
  category: "Image",
  tags: ["Creative", "Art", "Gallery"],
  logo: "https://openart.ai/favicon.ico",
  url: "https://openart.ai/",
  upvotes: 95,
  bookmarked: false
},
{
  id: 14,
  name: "Notion AI",
  description: "Enhance your note-taking and productivity with AI in Notion.",
  category: "Productivity",
  tags: ["Notes", "Writing", "Assistant"],
  logo: "https://www.notion.so/images/favicon.ico",
  url: "https://www.notion.so/product/ai",
  upvotes: 125,
  bookmarked: false
},
{
  id: 15,
  name: "Synthesia",
  description: "Create AI videos with avatars by typing text.",
  category: "Video",
  tags: ["Avatar", "Video", "Text-to-Video"],
  logo: "https://www.synthesia.io/favicon.ico",
  url: "https://www.synthesia.io/",
  upvotes: 118,
  bookmarked: false
},

{
  id: 16,
  name: "Claude",
  description: "Anthropic’s AI assistant designed to be helpful, honest, and harmless.",
  category: "Chat",
  tags: ["Chatbot", "NLP", "Assistant"],
  logo: "https://www.anthropic.com/favicon.ico",
  url: "https://claude.ai/",
  upvotes: 135,
  bookmarked: false
},
{
  id: 17,
  name: "DeepSeek",
  description: "Multilingual coding AI assistant based on open-source LLMs.",
  category: "Code",
  tags: ["Coding", "Multilingual", "LLM"],
  logo: "https://deepseek.com/favicon.ico",
  url: "https://deepseek.com/",
  upvotes: 92,
  bookmarked: false
},
{
  id: 18,
  name: "Bolt AI",
  description: "Bring ChatGPT to macOS with a beautiful native app.",
  category: "Productivity",
  tags: ["Mac", "ChatGPT", "Desktop App"],
  logo: "https://bolt.chat/favicon.ico",
  url: "https://bolt.chat/",
  upvotes: 85,
  bookmarked: false
},
{
  id: 19,
  name: "Recraft",
  description: "AI design tool to create vectors, illustrations, and 3D graphics.",
  category: "Design",
  tags: ["Design", "Graphics", "3D"],
  logo: "https://recraft.ai/favicon.ico",
  url: "https://www.recraft.ai/",
  upvotes: 100,
  bookmarked: false
},
{
  id: 20,
  name: "Magai",
  description: "Powerful ChatGPT interface for productivity and business use.",
  category: "Chat",
  tags: ["ChatGPT", "Productivity", "Business"],
  logo: "https://magai.co/favicon.ico",
  url: "https://magai.co/",
  upvotes: 88,
  bookmarked: false
},

{
  id: 21,
  name: "Ideogram",
  description: "AI tool for generating text-to-image content with creative typography.",
  category: "Image",
  tags: ["Text-to-Image", "Typography", "Creative"],
  logo: "https://ideogram.ai/favicon.ico",
  url: "https://ideogram.ai/",
  upvotes: 122,
  bookmarked: false
},
{
  id: 22,
  name: "Perplexity AI",
  description: "Answer engine powered by AI with sources and conversational follow-ups.",
  category: "Search",
  tags: ["Answers", "Search", "Assistant"],
  logo: "https://www.perplexity.ai/favicon.ico",
  url: "https://www.perplexity.ai/",
  upvotes: 140,
  bookmarked: false
},
{
  id: 23,
  name: "Pika Labs",
  description: "Generate and animate AI-powered videos easily.",
  category: "Video",
  tags: ["Animation", "Text-to-Video", "Creative"],
  logo: "https://www.pika.art/favicon.ico",
  url: "https://www.pika.art/",
  upvotes: 104,
  bookmarked: false
},
{
  id: 24,
  name: "HeyGen",
  description: "AI video generator with avatars and voiceovers for business use.",
  category: "Video",
  tags: ["Avatar", "Voice", "Business"],
  logo: "https://www.heygen.com/favicon.ico",
  url: "https://www.heygen.com/",
  upvotes: 113,
  bookmarked: false
},
{
  id: 25,
  name: "Mistral",
  description: "Open-weight LLM models for commercial and research use.",
  category: "LLM",
  tags: ["Open-Source", "LLM", "Research"],
  logo: "https://mistral.ai/favicon.ico",
  url: "https://mistral.ai/",
  upvotes: 101,
  bookmarked: false
},

{
  id: 26,
  name: "Jan",
  description: "Open-source AI chat app with local model support.",
  category: "Chat",
  tags: ["Open Source", "Local AI", "Privacy"],
  logo: "https://jan.ai/favicon.ico",
  url: "https://jan.ai/",
  upvotes: 87,
  bookmarked: false
},
{
  id: 27,
  name: "Cohere",
  description: "Provides powerful NLP APIs for enterprise and developers.",
  category: "LLM",
  tags: ["NLP", "Enterprise", "API"],
  logo: "https://cohere.ai/favicon.ico",
  url: "https://cohere.ai/",
  upvotes: 94,
  bookmarked: false
},
{
  id: 28,
  name: "Type.ai",
  description: "Collaborative AI-native document editor.",
  category: "Writing",
  tags: ["Writing", "Collaboration", "Docs"],
  logo: "https://type.ai/favicon.ico",
  url: "https://type.ai/",
  upvotes: 89,
  bookmarked: false
},
{
  id: 29,
  name: "Kaiber",
  description: "Generate cinematic videos from your ideas using AI.",
  category: "Video",
  tags: ["Video", "Cinematic", "Creative"],
  logo: "https://www.kaiber.ai/favicon.ico",
  url: "https://www.kaiber.ai/",
  upvotes: 98,
  bookmarked: false
},
{
  id: 30,
  name: "ElevenLabs",
  description: "AI voice synthesis and cloning with natural intonation.",
  category: "Audio",
  tags: ["Voice", "Cloning", "Synthesis"],
  logo: "https://www.elevenlabs.io/favicon.ico",
  url: "https://www.elevenlabs.io/",
  upvotes: 132,
  bookmarked: false
},
{
  id: 31,
  name: "Wisdolia",
  description: "Turn any webpage or PDF into smart flashcards.",
  category: "Education",
  tags: ["Flashcards", "Learning", "PDF"],
  logo: "https://wisdolia.com/favicon.ico",
  url: "https://wisdolia.com/",
  upvotes: 76,
  bookmarked: false
},
{
  id: 32,
  name: "Genei",
  description: "Summarize research papers and webpages instantly.",
  category: "Research",
  tags: ["Summarization", "Research", "Productivity"],
  logo: "https://www.genei.io/favicon.ico",
  url: "https://www.genei.io/",
  upvotes: 81,
  bookmarked: false
},
{
  id: 33,
  name: "Riffusion",
  description: "Generate music using AI with spectrograms.",
  category: "Audio",
  tags: ["Music", "Generation", "Creative"],
  logo: "https://www.riffusion.com/favicon.ico",
  url: "https://www.riffusion.com/",
  upvotes: 84,
  bookmarked: false
},
{
  id: 34,
  name: "Lex",
  description: "AI writing tool for focused, fast content creation.",
  category: "Writing",
  tags: ["Writer", "Editor", "Content"],
  logo: "https://lex.page/favicon.ico",
  url: "https://lex.page/",
  upvotes: 77,
  bookmarked: false
},
{
  id: 35,
  name: "KaChat",
  description: "AI agent powered by multiple LLMs for team collaboration.",
  category: "Chat",
  tags: ["Teams", "LLM", "Collaboration"],
  logo: "https://kachat.ai/favicon.ico",
  url: "https://kachat.ai/",
  upvotes: 70,
  bookmarked: false
},
{
  id: 36,
  name: "Luma AI",
  description: "Generate 3D models from photos or video using AI.",
  category: "3D",
  tags: ["3D", "Modeling", "Photogrammetry"],
  logo: "https://lumalabs.ai/favicon.ico",
  url: "https://lumalabs.ai/",
  upvotes: 93,
  bookmarked: false
},
{
  id: 37,
  name: "Veed.io",
  description: "Simple video editor with AI-powered tools.",
  category: "Video",
  tags: ["Video Editing", "Subtitles", "AI Tools"],
  logo: "https://www.veed.io/favicon.ico",
  url: "https://www.veed.io/",
  upvotes: 91,
  bookmarked: false
},
{
  id: 38,
  name: "Tome",
  description: "AI storytelling tool for building beautiful presentations.",
  category: "Presentation",
  tags: ["Presentations", "Storytelling", "Design"],
  logo: "https://tome.app/favicon.ico",
  url: "https://tome.app/",
  upvotes: 106,
  bookmarked: false
},
{
  id: 39,
  name: "Upword",
  description: "Summarize and research faster with AI note-taking.",
  category: "Research",
  tags: ["Summarization", "Note-Taking", "Learning"],
  logo: "https://upword.ai/favicon.ico",
  url: "https://upword.ai/",
  upvotes: 74,
  bookmarked: false
},
{
  id: 40,
  name: "Krea",
  description: "AI-assisted creative tool for artists and designers.",
  category: "Design",
  tags: ["Design", "Real-Time", "Creative"],
  logo: "https://krea.ai/favicon.ico",
  url: "https://krea.ai/",
  upvotes: 97,
  bookmarked: false
},
{
  id: 41,
  name: "Browse AI",
  description: "Train AI agents to scrape and monitor data from any website.",
  category: "Automation",
  tags: ["Web Scraping", "Monitoring", "No-Code"],
  logo: "https://www.browse.ai/favicon.ico",
  url: "https://www.browse.ai/",
  upvotes: 103,
  bookmarked: false
},
{
  id: 42,
  name: "AutoGPT",
  description: "Experimental open-source autonomous agent with memory and planning.",
  category: "Agent",
  tags: ["Autonomous", "Planning", "Open Source"],
  logo: "https://autogpt.net/favicon.ico",
  url: "https://github.com/Torantulino/Auto-GPT",
  upvotes: 119,
  bookmarked: false
},
{
  id: 43,
  name: "Genmo",
  description: "Create AI-generated video content with text prompts.",
  category: "Video",
  tags: ["Video", "Text-to-Video", "Animation"],
  logo: "https://genmo.ai/favicon.ico",
  url: "https://genmo.ai/",
  upvotes: 99,
  bookmarked: false
},
{
  id: 44,
  name: "Ink for All",
  description: "AI content optimizer for SEO and writing clarity.",
  category: "Marketing",
  tags: ["SEO", "Writing", "Optimization"],
  logo: "https://inkforall.com/favicon.ico",
  url: "https://inkforall.com/",
  upvotes: 90,
  bookmarked: false
},
{
  id: 45,
  name: "Papercup",
  description: "Translate and voice-over videos using AI dubbing.",
  category: "Audio",
  tags: ["Translation", "Voice", "Localization"],
  logo: "https://www.papercup.com/favicon.ico",
  url: "https://www.papercup.com/",
  upvotes: 86,
  bookmarked: false
},
{
  id: 46,
  name: "Booth AI",
  description: "Generate studio-quality product photos using AI.",
  category: "Image",
  tags: ["Product", "Photo", "Studio"],
  logo: "https://www.booth.ai/favicon.ico",
  url: "https://www.booth.ai/",
  upvotes: 83,
  bookmarked: false
},
{
  id: 47,
  name: "Illustroke",
  description: "Create stunning vector illustrations from text prompts.",
  category: "Design",
  tags: ["Vector", "Text-to-Image", "Creative"],
  logo: "https://illustroke.com/favicon.ico",
  url: "https://illustroke.com/",
  upvotes: 78,
  bookmarked: false
},
{
  id: 48,
  name: "Tabnine",
  description: "AI assistant for code completion trained on open-source projects.",
  category: "Code",
  tags: ["Coding", "IDE", "Completion"],
  logo: "https://www.tabnine.com/favicon.ico",
  url: "https://www.tabnine.com/",
  upvotes: 95,
  bookmarked: false
},
{
  id: 49,
  name: "Codeium",
  description: "Free AI-powered coding assistant with fast autocompletion.",
  category: "Code",
  tags: ["Coding", "Autocompletion", "Free"],
  logo: "https://codeium.com/favicon.ico",
  url: "https://codeium.com/",
  upvotes: 91,
  bookmarked: false
},
{
  id: 50,
  name: "Phind",
  description: "AI search engine designed for developers.",
  category: "Search",
  tags: ["Developer", "Search", "Assistant"],
  logo: "https://www.phind.com/favicon.ico",
  url: "https://www.phind.com/",
  upvotes: 110,
  bookmarked: false
}

];
